name: AffixForge
version: '${version}'

main: com.voc2048.affixForge.AffixForge
api-version: '26.2'
load: POSTWORLD

commands:
  affix:
    description: "Affix management command"
    usage: "/affix give <quality>"
    permission: "affixforge.admin"
