name: AffixForge
version: '${version}'

main: com.voc2048.affixForge.AffixForge
api-version: '1.21'
load: POSTWORLD

commands:
  affix:
    description: "Affix management command"
    usage: "/affix"
    permission: "affixforge.admin"
    aliases: [affixforge]
